version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: '${BACKEND_HOST}'
        VITE_DASHBOARD_URL: ${DASHBOARD_URL}
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - web-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_NAME: ${DB_NAME}
        SECRET_KEY: ${SECRET_KEY}
        FRONTEND_URL: '${FRONTEND_HOST}'
        DEEPL_APIKEY: ${DEEPL_APIKEY}
    depends_on:
      - db
    networks:
      - internal
      - web-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - internal
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  internal:
  web-network:
    external: true
